In [1]:
%pip uninstall pandas -y

Found existing installation: pandas 3.0.6
Uninstalling pandas-3.0.6:
  Successfully uninstalled pandas-3.0.6
Note: you may need to restart the kernel to use updated packages.

In [ ]:
%pip install pandas

In [1]:
import pandas as pd

In [3]:
pd.Series([28,30,32,31,29])

0    28
1    30
2    32
3    31
4    29
dtype: int64

In [4]:
temperture_series=pd.Series([28,30,32,31,29])

In [5]:
temperture_series

0    28
1    30
2    32
3    31
4    29
dtype: int64

In [6]:
data={
    "temperature" :[28,30,32,31,29],
    "rainfall" :[12,25,18,40,32],
    "ndvi" :[0.45,0.52,0.61,0.48,0.55]
}

In [8]:
df=pd.DataFrame(data)

In [9]:
df

   temperature  rainfall  ndvi
0           28        12  0.45
1           30        25  0.52
2           32        18  0.61
3           31        40  0.48
4           29        32  0.55

In [10]:
df=pd.read_csv("environmental_data.csv")

In [11]:
df.head()

,station_id,date,region,latitude,longitude,temperature,rainfall,ndvi,elevation
0,ST01,01-06-2026,North,28.61,77.21,34.2,12.5,0.32,216
1,ST02,01-06-2026,South,13.08,80.27,31.4,45.2,0.58,6
2,ST03,01-06-2026,East,20.30,85.82,32.1,28.4,0.51,42
3,ST04,01-06-2026,West,19.07,72.87,33.5,18.7,0.39,14
4,ST05,02-06-2026,North,28.70,77.10,35.1,8.2,0.29,228

In [12]:
df.head(12)

,station_id,date,region,latitude,longitude,temperature,rainfall,ndvi,elevation
0,ST01,01-06-2026,North,28.61,77.21,34.2,12.5,0.32,216
1,ST02,01-06-2026,South,13.08,80.27,31.4,45.2,0.58,6
2,ST03,01-06-2026,East,20.30,85.82,32.1,28.4,0.51,42
3,ST04,01-06-2026,West,19.07,72.87,33.5,18.7,0.39,14
4,ST05,02-06-2026,North,28.70,77.10,35.1,8.2,0.29,228
5,ST06,02-06-2026,South,12.97,77.59,29.8,52.6,0.64,920
6,ST07,02-06-2026,East,22.57,88.36,33.0,36.5,0.55,9
7,ST08,02-06-2026,West,18.52,73.86,30.7,22.1,0.47,560
8,ST09,03-06-2026,North,26.85,80.95,33.6,15.4,0.41,123
9,ST10,03-06-2026,South,11.02,76.96,28.9,61.3,0.72,40
10,ST11,03-06-2026,East,21.17,86.65,31.8,42.7,0.60,31
11,ST12,03-06-2026,West,23.02,72.57,36.0,10.6,0.27,53

In [13]:
df.shape

(30, 9)

In [14]:
df.columns

Index(['station_id', 'date', 'region', 'latitude', 'longitude', 'temperature',
       'rainfall', 'ndvi', 'elevation'],
      dtype='str')

In [15]:
df["temperature"]

0     34.2
1     31.4
2     32.1
3     33.5
4     35.1
5     29.8
6     33.0
7     30.7
8     33.6
9     28.9
10    31.8
11    36.0
12    27.5
13    30.2
14    34.0
15    32.8
16    26.9
17    32.5
18    33.1
19    37.2
20    24.8
21    29.1
22    35.0
23    29.7
24    34.7
25    30.8
26    25.6
27    33.4
28    35.5
29    31.0
Name: temperature, dtype: float64

In [17]:
df[["temperature","rainfall","ndvi"]]

    temperature  rainfall  ndvi
0          34.2      12.5  0.32
1          31.4      45.2  0.58
2          32.1      28.4  0.51
3          33.5      18.7  0.39
4          35.1       8.2  0.29
5          29.8      52.6  0.64
6          33.0      36.5  0.55
7          30.7      22.1  0.47
8          33.6      15.4  0.41
9          28.9      61.3  0.72
10         31.8      42.7  0.60
11         36.0      10.6  0.27
12         27.5      24.8  0.53
13         30.2      48.9  0.69
14         34.0      31.6  0.44
15         32.8      17.3  0.36
16         26.9      29.7  0.57
17         32.5      39.4  0.50
18         33.1      27.9  0.62
19         37.2       5.8  0.22
20         24.8      34.2  0.66
21         29.1      74.5  0.78
22         35.0      21.5  0.38
23         29.7      55.1  0.71
24         34.7      11.9  0.34
25         30.8      46.3  0.59
26         25.6      68.2  0.75
27         33.4      14.7  0.31
28         35.5       9.6  0.37
29         31.0      58.7  0.67

In [18]:
df[df["temperature"]>30]

,station_id,date,region,latitude,longitude,temperature,rainfall,ndvi,elevation
0,ST01,01-06-2026,North,28.61,77.21,34.2,12.5,0.32,216
1,ST02,01-06-2026,South,13.08,80.27,31.4,45.2,0.58,6
2,ST03,01-06-2026,East,20.30,85.82,32.1,28.4,0.51,42
3,ST04,01-06-2026,West,19.07,72.87,33.5,18.7,0.39,14
4,ST05,02-06-2026,North,28.70,77.10,35.1,8.2,0.29,228
6,ST07,02-06-2026,East,22.57,88.36,33.0,36.5,0.55,9
7,ST08,02-06-2026,West,18.52,73.86,30.7,22.1,0.47,560
8,ST09,03-06-2026,North,26.85,80.95,33.6,15.4,0.41,123
10,ST11,03-06-2026,East,21.17,86.65,31.8,42.7,0.60,31
11,ST12,03-06-2026,West,23.02,72.57,36.0,10.6,0.27,53
13,ST14,04-06-2026,South,15.50,73.83,30.2,48.9,0.69,22
14,ST15,04-06-2026,East,25.59,85.14,34.0,31.6,0.44,53
15,ST16,04-06-2026,West,21.15,79.09,32.8,17.3,0.36,310
17,ST18,05-06-2026,South,17.39,78.49,32.5,39.4,0.50,505
18,ST19,05-06-2026,East,19.81,85.83,33.1,27.9,0.62,12
19,ST20,05-06-2026,West,26.91,75.79,37.2,5.8,0.22,431
22,ST23,06-06-2026,East,23.26,77.41,35.0,21.5,0.38,527
24,ST25,07-06-2026,North,27.18,78.02,34.7,11.9,0.34,171
25,ST26,07-06-2026,South,20.30,85.82,30.8,46.3,0.59,42
27,ST28,07-06-2026,West,22.31,73.18,33.4,14.7,0.31,92
28,ST29,08-06-2026,North,25.44,81.85,35.5,9.6,0.37,98
29,ST30,08-06-2026,South,14.47,78.82,31.0,58.7,0.67,269

In [19]:
df[df["ndvi"]>0.5]

,station_id,date,region,latitude,longitude,temperature,rainfall,ndvi,elevation
1,ST02,01-06-2026,South,13.08,80.27,31.4,45.2,0.58,6
2,ST03,01-06-2026,East,20.30,85.82,32.1,28.4,0.51,42
5,ST06,02-06-2026,South,12.97,77.59,29.8,52.6,0.64,920
6,ST07,02-06-2026,East,22.57,88.36,33.0,36.5,0.55,9
9,ST10,03-06-2026,South,11.02,76.96,28.9,61.3,0.72,40
10,ST11,03-06-2026,East,21.17,86.65,31.8,42.7,0.60,31
12,ST13,04-06-2026,North,30.32,78.03,27.5,24.8,0.53,640
13,ST14,04-06-2026,South,15.50,73.83,30.2,48.9,0.69,22
16,ST17,05-06-2026,North,29.95,78.16,26.9,29.7,0.57,430
18,ST19,05-06-2026,East,19.81,85.83,33.1,27.9,0.62,12
20,ST21,06-06-2026,North,31.10,77.17,24.8,34.2,0.66,1520
21,ST22,06-06-2026,South,9.93,76.27,29.1,74.5,0.78,8
23,ST24,06-06-2026,West,15.30,74.12,29.7,55.1,0.71,590
25,ST26,07-06-2026,South,20.30,85.82,30.8,46.3,0.59,42
26,ST27,07-06-2026,East,24.82,93.94,25.6,68.2,0.75,786
29,ST30,08-06-2026,South,14.47,78.82,31.0,58.7,0.67,269

In [20]:
df[
    (df["temperature"]>30)&
    (df["ndvi"]>0.5)&
     (df["rainfall"]>40)
    ]

,station_id,date,region,latitude,longitude,temperature,rainfall,ndvi,elevation
1,ST02,01-06-2026,South,13.08,80.27,31.4,45.2,0.58,6
10,ST11,03-06-2026,East,21.17,86.65,31.8,42.7,0.60,31
13,ST14,04-06-2026,South,15.50,73.83,30.2,48.9,0.69,22
25,ST26,07-06-2026,South,20.30,85.82,30.8,46.3,0.59,42
29,ST30,08-06-2026,South,14.47,78.82,31.0,58.7,0.67,269

In [21]:
df.groupby("region")["temperature"].mean()

region
East     32.085714
North    31.537500
South    30.462500
West     33.328571
Name: temperature, dtype: float64

In [22]:
df["region"].value_counts()

region
North    8
South    8
East     7
West     7
Name: count, dtype: int64